FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    software-properties-common \	       
    build-essential \     
    python3 python3-pip python-is-python3 \
    minimap2 gawk git wget zlib1g-dev libbz2-dev liblzma-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pysam pyfastaq pymysql cluster_vcf_records python-dateutil openpyxl xlsxwriter requests

RUN wget -q https://github.com/alastair-droop/fqtools/archive/refs/tags/v2.3.tar.gz && \
    tar xf v2.3.tar.gz && \
    rm v2.3.tar.gz && \
    cd fqtools-2.3/  && \
    wget -q https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2 && \
    tar xf htslib-1.17.tar.bz2 && \
    rm htslib-1.17.tar.bz2 && \
    cd htslib-1.17 && \
    ./configure . && \
    make && \
    make install && \
    cd .. && \
    make CC=gcc HTSDIR=./htslib-1.17/ CPPFLAGS+=-fcommon

COPY . /opt/clockwork

ENV PYTHONPATH=$PYTHONPATH:/opt/clockwork/python
ENV PATH=$PATH:/opt/clockwork/python/scripts:/fqtools-2.3/bin
